language: node_js
node_js:
    - '12'
services:
    - docker
cache:
    # npm is cached by default
    directories:
        - node_modules
script:
    - npm test
before_deploy:
    - npm i -g travis-ci-cloudfront-invalidation
    - npm run build
    - docker image build -t $DOCKER_HUB_REPO .
    - bash scripts/docker_push.sh
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local-dir: build
    on:
        branch: master
after_deploy:
    - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
